import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import BackToTopButton from "@/components/back-to-top"
import Footer from "@/components/footer"
import NavBar from "@/components/nav-bar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased leading-normal break-words transition-colors duration-500`}
      >
        <NavBar />
        <main className="pt-20">
          <article className="prose prose-lg md:prose-xl prose-zinc dark:prose-invert prose-a:no-underline mx-auto max-w-5xl px-8">
            {children}
          </article>
        </main>
        <BackToTopButton />
        <Footer />
      </body>
    </html>
  )
}
